ATK_RANGE = 3
N_TEAM = 16
N_PLAYER_PER_TEAM = 8
N_PROF = 8
N_TILE_TYPE = 16
N_PLAYER = N_TEAM * N_PLAYER_PER_TEAM
MAX_STEP = 1024
TERRAIN_SIZE = 160
HALF_TERRAIN_SIZE = TERRAIN_SIZE // 2
MAP_LEFT = 16
MAP_RIGHT = 144
MAP_SIZE = MAP_RIGHT - MAP_LEFT + 1
WINDOW = 15
WINDOW_CENTER = 7
PASSABLE_TILES = [2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13]
OBSTACLE_TILES = [t for t in range(N_TILE_TYPE) if t not in PASSABLE_TILES]

NEGATIVE_POP = -1
NEUTRAL_POP = -2
HOSTILE_POP = -3

TILE_LAVA = 0
TILE_WATER = 1
TILE_GRASS = 2
TILE_SCRUB = 3
TILE_FOREST = 4
TILE_STONE = 5
TILE_SLAG = 6
TILE_ORE = 7
TILE_STUMP = 8
TILE_TREE = 9
TILE_FRAGMENT = 10
TILE_CRYSTAL = 11
TILE_WEEDS = 12
TILE_HERB = 13
TILE_OCEAN = 14
TILE_FISH = 15
TILE_UNEXPLORE = 16

EQUIPMENT = [
    'HatLevel',
    'BottomLevel',
    'TopLevel',
    'HeldLevel',
    'AmmunitionLevel',
]
ATK_TYPE = [
    'Melee',
    'Range',
    'Mage',
]
N_ATK_TYPE = len(ATK_TYPE)

IDX_ENT_MASK = 0
IDX_ENT_ENTITY_ID = 1
IDX_ENT_ATTACKER_ID = 2
IDX_ENT_LVL = 3
IDX_ENT_ITEM_LVL = 4
IDX_ENT_COMM = 5
IDX_ENT_POPULATION = 6
IDX_ENT_ROW_INDEX = 7
IDX_ENT_COL_INDEX = 8
IDX_ENT_DAMAGE = 9
IDX_ENT_TIME_ALIVE = 10
IDX_ENT_FREEZE = 11
IDX_ENT_GOLD = 12
IDX_ENT_HEALTH = 13
IDX_ENT_FOOD = 14
IDX_ENT_WATER = 15
IDX_ENT_MELEE_LVL = 16
IDX_ENT_RANGE_LVL = 17
IDX_ENT_MAGE_LVL = 18
IDX_ENT_FISHING_LVL = 19
IDX_ENT_HERBALISM_LVL = 20
IDX_ENT_PROSPECTING_LVL = 21
IDX_ENT_CARVING_LVL = 22
IDX_ENT_ALCHEMY_LVL = 23

IDX_TO_NAME = {i: name for i, name in enumerate(list(filter(lambda s: s.startswith('IDX_ENT'), globals())))}

IDX_ITEM_ID = 0
IDX_ITEM_INDEX = 1
IDX_ITEM_LEVEL = 2
IDX_ITEM_CAPACITY = 3
IDX_ITEM_QUANTITY = 4
IDX_ITEM_TRADABLE = 5
IDX_ITEM_MELEE_ATK = 6
IDX_ITEM_RANGE_ATK = 7
IDX_ITEM_MAGE_ATK = 8
IDX_ITEM_MELEE_DEF = 9
IDX_ITEM_RANGE_DEF = 10
IDX_ITEM_MAGE_DEF = 11
IDX_ITEM_HP_RST = 12
IDX_ITEM_RSC_RST = 13
IDX_ITEM_PRICE = 14
IDX_ITEM_EQUIPPED = 15

N_ITEM_LVL = 10
N_ITEM_SLOT = 12
N_ITEM_TYPE = 17
N_ITEM_LIMIT = 11  # if surpass the limit, automatically sell one

ITEM_GOLD = 1
ITEM_HAT = 2  # Armor
ITEM_TOP = 3  # Armor
ITEM_BOTTOM = 4  # Armor
ITEM_SWORD = 5  # Weapon
ITEM_BOW = 6  # Weapon
ITEM_WAND = 7  # Weapon
ITEM_ROD = 8  # Tool
ITEM_GLOVES = 9  # Tool
ITEM_PICKAXE = 10  # Tool
ITEM_CHISEL = 11  # Tool
ITEM_ARCANE = 12  # Tool
ITEM_SCRAP = 13  # Ammunition
ITEM_SHAVING = 14  # Ammunition
ITEM_SHARD = 15  # Ammunition
ITEM_RATION = 16  # Consumable
ITEM_POULTICE = 17  # Consumable

ITEM_TO_PROF_IDX = {
    ITEM_SWORD: IDX_ENT_MELEE_LVL,
    ITEM_BOW: IDX_ENT_RANGE_LVL,
    ITEM_WAND: IDX_ENT_MAGE_LVL,
    ITEM_SCRAP: IDX_ENT_MELEE_LVL,
    ITEM_SHAVING: IDX_ENT_RANGE_LVL,
    ITEM_SHARD: IDX_ENT_MAGE_LVL,
    ITEM_ROD: IDX_ENT_FISHING_LVL,
    ITEM_GLOVES: IDX_ENT_HERBALISM_LVL,
    ITEM_PICKAXE: IDX_ENT_PROSPECTING_LVL,
    ITEM_CHISEL: IDX_ENT_CARVING_LVL,
    ITEM_ARCANE: IDX_ENT_ALCHEMY_LVL,
}

ARMORS = {
    ITEM_HAT,
    ITEM_TOP,
    ITEM_BOTTOM,
}

WEAPONS = {
    ITEM_SWORD,
    ITEM_WAND,
    ITEM_BOW,
}

TOOLS = {
    ITEM_ROD,
    ITEM_GLOVES,
    ITEM_PICKAXE,
    ITEM_CHISEL,
    ITEM_ARCANE,
}

AMMOS = {
    ITEM_SCRAP,
    ITEM_SHAVING,
    ITEM_SHARD,
}

CONSUMABLES = {
    ITEM_RATION,
    ITEM_POULTICE,
}

ATK_TO_WEAPON = {
    'Melee': ITEM_SWORD,
    'Range': ITEM_BOW,
    'Mage': ITEM_WAND,
}

ATK_TO_TOOL = {
    'Melee': ITEM_PICKAXE,
    'Range': ITEM_CHISEL,
    'Mage': ITEM_ARCANE,
}

ATK_TO_TILE = {
    'Melee': 7,  # Ore
    'Range': 9,  # Tree
    'Mage': 11,  # Crystal
}

PROF_TO_ATK_TYPE = {
    'Melee': 0,
    'Range': 1,
    'Mage': 2,
}
